<a href="https://colab.research.google.com/github/yesomac/MinimalTheme/blob/main/ArrayNumpay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manupulandos List -> py como Array -> Pnadas

In [3]:
import numpy as np

## Definicion list y transformacion a array

In [4]:
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
#lista a array de numpy
arr = np.array(lista)

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
#matriz a array
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(arr[0] + arr[5])

5


In [11]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(matriz[0])
print(matriz[1])
print(matriz[0][0])

[1 2 3]
[4 5 6]
1


## Recorriendo el array con pandas en una matriz

Para navegar en una matriz con numpy debemos separar por coma sus filas y columnas, por ejemplo para sumar los elementos de la primer fila

Con python normalmente podriamos:
```sh
print(matriz[0][0] + matriz[0][1] + matriz[0][2]) #6
```

Ahora numpy facilita esta misma operacion de la siguiente manera
```sh
print(matriz[0, 0] + matriz[0, 1] + matriz[0, 2]) #6
```

In [22]:
#Para navegar por coli
print(matriz[0][0] + matriz[0][1] + matriz[0][2])
print(matriz[0, 0] + matriz[0, 1] + matriz[0, 2])

6
6


## Slicing con arr

matriz[inicio : fin : salto , inicio : fin : salto]

In [29]:
print(arr)

#con slicing
print(arr[0:3])

print(arr[3:10])

print(arr[:5])

print(arr[5:])

print(arr[-1])

print(arr[-3:])

#recorrido de todo el arreglo por pasos, en este caso por 3
print(arr)
print(arr[::3])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
9
[7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


Slicing con matrices

In [33]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(matriz[1:,0:2])

[[4 5]
 [7 8]]


## Experimentando con matrices X3

In [48]:
mat = [[[1,2,3], [4,5,6], [7,8,9]],[[2,4,6],[8,10,12],[14,16,18]], [[3,6,9],[12,15,18], [21,23,26]] ]
mat = np.array(mat)

In [49]:
print(mat)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 3  6  9]
  [12 15 18]
  [21 23 26]]]


In [50]:
print(mat[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(mat[0,0,0])
print(mat[1,0,0])
print(mat[2,0,0])

1
2
3


In [57]:
print(mat[0,0,0] + mat[1,0,0] + mat[2,0,0])

6


In [59]:
print(mat)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 3  6  9]
  [12 15 18]
  [21 23 26]]]


In [61]:
print(mat[0,0,:3])

[1 2 3]


In [63]:
print(mat[1,2,:3])

[14 16 18]


In [66]:
print(mat[2,1,2:])

[18]


In [67]:
print(mat[0, :, 2])

[3 6 9]


# Tipos de datos


In [67]:
import numpy as np

Con dtype podemos
* Conocer el tipo de dato del contenido de una variables
* Cambiar manualmente el tipo de dato de dicha variable

In [69]:
#definiendo un array
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


Para realizar el cambio del tipo de dato en la creacion del mismo despues de una coma especificamos entre comillas el tipo a transformar
* dtype='float64'

In [80]:
#cambiando el tipo de int64 a float64
arr2 = np.array([0, 1, 2, 3, 4], dtype='float64')
print(arr2)
print(arr2.dtype)

[0. 1. 2. 3. 4.]
float64


Conversion del tipo de tado directamente desde la libreria

In [81]:
from numpy.core.memmap import dtype
arr3 = arr2.astype(np.float64)
print(arr3)
print(arr3.dtype)

[0. 1. 2. 3. 4.]
float64


Cambiando el dato de float a bool

In [82]:
print(f'Float:{arr3}')
print(f'Boll:{arr3.astype(np.bool_)}')

Float:[0. 1. 2. 3. 4.]
Boll:[False  True  True  True  True]


Cnoversion a string

In [85]:
print(f'Boll:{arr3.astype(np.bool_)}')
print(f'String:{arr3.astype(np.string_)}')

Boll:[False  True  True  True  True]
String:[b'0.0' b'1.0' b'2.0' b'3.0' b'4.0']


Conversion string a int8, solo la hara la conversion  de datos numericos validos

In [91]:
arr_str = np.array(['0', '1', '2', '3', '4'])
print(f'String:{arr_str}')
arr_str_int = arr_str.astype(np.int8)
print(f'Int8:{arr_str_int}')

String:['0' '1' '2' '3' '4']
Int8:[0 1 2 3 4]


Creando un array con arange

In [92]:
arr_ge = np.arange(0, 10)
print(arr_ge)

[0 1 2 3 4 5 6 7 8 9]


# Dimensiones

Dimensiones de los datos
* Un dato -> Scalar
* Una lista -> Vector
* Una  Vector de dos dimensiones -> Matrix
* Dimensiones cada vez mas grandes -> Tensor



In [1]:
import numpy as np

Scalar -> 0

In [2]:
scalar = np.array(42)
print(f'Scalar:{scalar}')
print(f'Dimensiones:{scalar.ndim}')

Scalar:42
Dimensiones:0


Vector -> 1

In [4]:
vector = np.array([2, 1,4,2])
print(f'vector:{vector}')
print(f'Dimensiones:{vector.ndim}')

vector:[2 1 4 2]
Dimensiones:1


Matrix

In [6]:
matriz = np.array([[1,2,3,4], [5,6,7,8]])
print(f'matriz:{matriz}')
print(f'Dimensiones:{matriz.ndim}')

matriz:[[1 2 3 4]
 [5 6 7 8]]
Dimensiones:2


In [7]:
matriz = np.array([[1,2,3,4], [5,6,7,8],[1,2,3,4], [5,6,7,8]])
print(f'matriz:{matriz}')
print(f'Dimensiones:{matriz.ndim}')

matriz:[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
Dimensiones:2


Tensor

In [10]:
tensor = np.array([[[1,2,3,4], [5,6,7,8],[1,2,3,4], [5,6,7,8], [1,2,3,4], [5,6,7,8],[1,2,3,4], [5,6,7,8]]])
print(f'tensor:{tensor}')
print(f'Dimensiones:{tensor.ndim}')

tensor:[[[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]]]
Dimensiones:3


In [12]:
tensor = np.array([[[1,2,3,4], [5,6,7,8],[1,2,3,4], [5,6,7,8], [1,2,3,4], [5,6,7,8],[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [5,6,7,8],[1,2,3,4], [5,6,7,8], [1,2,3,4], [5,6,7,8],[1,2,3,4], [5,6,7,8]]])
print(f'tensor:{tensor}')
print(f'Dimensiones:{tensor.ndim}')

tensor:[[[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]]]
Dimensiones:3


## Agregar o eliminar dimensiones

### Agregar

In [13]:
vector = np.array([1, 2, 3])
print(f'Vector inicial: {vector}')

Vector inicial: [1 2 3]


In [14]:
vector = np.array([1, 2, 3], ndmin=10)
print(f'Vector ahora de 10 dimensiones: {vector}')

Vector ahora de 10 dimensiones: [[[[[[[[[[1 2 3]]]]]]]]]]


In [ ]:
vector = np.array([1, 2, 3])
print(f'Vector inicial: {vector}')

Expandir una unica dimension
axis=0 hace referencia a la expansion a nivel de filas, de ser a nivel de columnas axis debe ser igualado a 1 axis=1

In [15]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(f'Expandiendo una unica dimension:{expand}')
expand.ndim

Expandiendo una unica dimension:[[1 2 3]]


2

### Eliminar

squeeze lo que hace es compirmir el vector al numero de dimensiones correctas, por ejemplo en este caso pasa de 10 dimensiones a 1 ya que el numero de dimensiones idioneo es 1 por la cantidad de datos

In [16]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


### 5 dimensiones

Pasando un tensor con dimension 5 a 6 y de 6 al numero de dimensiones ideal de acuerdo a su estructura
* Definicion del vector
* Axis para ampliar las dimesiones
* Squeeze para remover el numero de dimensiones inicesarias

In [17]:
tensor2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], ndmin=5)
print(tensor2)
print(tensor2.ndim)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5


In [18]:
tensor2 = np.expand_dims(tensor2, axis=1)
print(tensor2)
print(tensor2.ndim)

[[[[[[1 2 3]
     [4 5 6]
     [7 8 9]]]]]]
6


In [20]:
tensor2 = np.squeeze(tensor2)
print(tensor2)
print(tensor.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


# Creando Arrays con numpy

In [21]:
import numpy as np

Generacion de una lista con py

In [22]:
li = list(range(0,10))
print(li)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Generacion de un array con numpy

In [23]:
arr = np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### arange
* Prinera posicion -> valor inicial
* Segunda posicion -> valor final
* Tercer posicion -> iteracion

In [24]:
arr = np.arange(0,22,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


### Defincion de un array por ceros

In [45]:
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [29]:
arr = np.zeros((10, 10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
arr = np.ones((10, 22))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Linespace
* Prinera posicion -> valor inicial
* Segunda posicion -> valor final
* Tercer posicion -> numero de valores a general

In [36]:
arr = np.linspace(0, 11, 10)
print(arr)

[ 0.          1.22222222  2.44444444  3.66666667  4.88888889  6.11111111
  7.33333333  8.55555556  9.77777778 11.        ]


In [37]:
arr = np.linspace(0, 11, 100)
print(arr)

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.          1.11111111  1.22222222
  1.33333333  1.44444444  1.55555556  1.66666667  1.77777778  1.88888889
  2.          2.11111111  2.22222222  2.33333333  2.44444444  2.55555556
  2.66666667  2.77777778  2.88888889  3.          3.11111111  3.22222222
  3.33333333  3.44444444  3.55555556  3.66666667  3.77777778  3.88888889
  4.          4.11111111  4.22222222  4.33333333  4.44444444  4.55555556
  4.66666667  4.77777778  4.88888889  5.          5.11111111  5.22222222
  5.33333333  5.44444444  5.55555556  5.66666667  5.77777778  5.88888889
  6.          6.11111111  6.22222222  6.33333333  6.44444444  6.55555556
  6.66666667  6.77777778  6.88888889  7.          7.11111111  7.22222222
  7.33333333  7.44444444  7.55555556  7.66666667  7.77777778  7.88888889
  8.          8.11111111  8.22222222  8.33333333  8.44444444  8.55555556
  8.66666667  8.77777778  8.88888889  9.          9

### Matriz 4 * 4

In [38]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Valores aleatorio

In [40]:
np.random.rand()

0.739500527423516

In [41]:
np.random.rand(4)

array([0.00521043, 0.17847171, 0.6608017 , 0.46740772])

In [42]:
np.random.rand(4,4)

array([[0.12396485, 0.69269058, 0.2846455 , 0.66802689],
       [0.23630049, 0.96865847, 0.79762348, 0.97664985],
       [0.36565238, 0.4974646 , 0.12824545, 0.66152979],
       [0.38234424, 0.19537674, 0.8656109 , 0.80425738]])

### Entero aleatorio

In [46]:
np.random.randint(1, 15)

7

In [44]:
np.random.randint(1, 100, (10,19))

array([[19, 67, 34, 51, 87, 88, 11, 29, 51, 64, 38, 55, 75, 89, 52,  7,
        42, 87,  2],
       [ 1, 18, 48, 16, 83, 14, 19, 97, 84, 29, 41, 86, 43, 80, 89, 76,
        51, 54, 51],
       [73, 21, 64, 51, 93, 47,  8,  1, 15, 95, 18, 92, 55, 38, 75, 89,
        69, 75, 84],
       [50,  6, 14, 51, 16, 82, 87, 88, 35, 98, 32, 73, 16, 66, 76, 59,
        44, 93, 24],
       [88, 32, 62, 76, 45,  4, 28, 64, 13, 67, 54,  9, 85, 13, 36, 40,
        24, 21, 23],
       [27, 61, 20, 66, 59, 73, 56, 86, 50, 26, 13, 23, 76, 14, 46, 84,
        74, 21, 99],
       [87, 28, 89, 55, 47, 32, 75, 79, 34, 19, 70, 14, 17, 25, 48, 85,
        59, 34, 77],
       [65, 87, 53, 43, 65, 39, 37, 23,  4,  3, 52, 10, 22, 38, 63, 78,
        78, 53, 89],
       [ 4, 32, 73, 80, 90, 99, 43,  1, 86, 50, 94,  4, 17, 97, 63, 96,
        13, 21, 59],
       [76, 83, 61, 15, 20, 35, 91, 19, 54, 91, 99, 83, 61, 50, 81,  7,
        88, 99, 48]])

# Shape y Reshape


In [4]:
import numpy as np

In [5]:
arr = np.random.randint(1, 10, (3, 2))
print(f'Array aleatorio de 1 a 10 con una dimension de 3x2')
print(arr)

Array aleatorio de 1 a 10 con una dimension de 3x2
[[1 5]
 [8 1]
 [9 6]]


### Shape
Shape retorna el tamaño o numero de dimensiones del arreglo, la forma que tiene el arreglo en si

In [6]:
print(f'Cual es la dimension del arreglo?:{arr.shape}')

Cual es la dimension del arreglo?:(3, 2)


### Reshape
Cambia la forma establecida en un array definido anteriormente, en ejemplo, cambia el arreglo de 3x2 a 1x6.

Para aplicar reshape es sustancial respetar el tamaño del array, es decir no aplica si es mas grande.

In [8]:
arr2 = arr.reshape(1, 6)
print(arr2)

[[1 5 8 1 9 6]]


In [10]:
print(np.reshape(arr2, (2, 3)))

[[1 5 8]
 [1 9 6]]


Hacer reshape como en lenguaje c -> por filas

In [54]:
np.reshape(arr2, (2,3), 'C')

array([[3, 2, 5],
       [6, 2, 9]])

Hacer reshape como en lenguaje foltran -> por columnas

In [55]:
np.reshape(arr2, (2,3), 'F')

array([[3, 5, 2],
       [2, 6, 9]])

Hacer reshape como mejor este optimzado para el sistema op en el que este corriendo

In [56]:
np.reshape(arr2, (2,3), 'A')

array([[3, 2, 5],
       [6, 2, 9]])

# Funciones principales de Numpy

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)
print(arr)

[ 3 14 12  4  3  5 10 18  6 15]


In [3]:
matriz = arr.reshape(2, 5)
print(matriz)

[[ 3 14 12  4  3]
 [ 5 10 18  6 15]]


#### Max
Retorna el numero mas grande del array

In [5]:
print(arr)
arr.max()

[ 3 14 12  4  3  5 10 18  6 15]


18

En matrices podemos obtener el mayor de cada fila indicandole el eje. Por ejemplo en el eje:
* 1 lo hace obtebiendo el mayor de cada fila
* 0 lo hace por columnas

In [9]:
print(matriz)
matriz.max()
matriz.max(1)
matriz.max(0)

[[ 3 14 12  4  3]
 [ 5 10 18  6 15]]


array([ 5, 14, 18,  6, 15])

##### Indice del valor mas grande
Por ejemplo para el array = 
```sh
[ 3 14 12  4  3  5 10 18  6 15]
arr.argmax()
-> 7
```
Para el ejemplo la funcion armax() retorna una posicion, en este caso el valor mas grande se encuentra en la posicion numero 7 siendo este el numero 18

In [15]:
print(arr)
arr.argmax()

[ 3 14 12  4  3  5 10 18  6 15]


7

En el caso de las matrices

In [16]:
print(matriz)
matriz.argmax()

[[ 3 14 12  4  3]
 [ 5 10 18  6 15]]


7

De igual menera podemos consultar el mayor por fila y por columna

In [22]:
print(matriz)
print(f'Mayor por columna:{matriz.max(0)}')

[[ 3 14 12  4  3]
 [ 5 10 18  6 15]]
Mayor por columna:[ 5 14 18  6 15]


In [23]:
print(matriz)
print(f'Mayor por columna:{matriz.max(1)}')

[[ 3 14 12  4  3]
 [ 5 10 18  6 15]]
Mayor por columna:[14 18]


##### Indice del valor mas pequeño
De igual manera tenemos la funcion min la cual retorna el valor mas pequeño del array o matriz

In [24]:
print(arr)

[ 3 14 12  4  3  5 10 18  6 15]


In [25]:
arr.min()

3

In [27]:
arr.argmin()

0

In [29]:
print(matriz)

[[ 3 14 12  4  3]
 [ 5 10 18  6 15]]


In [32]:
matriz.min()

3

In [33]:
matriz.min(0)

array([ 3, 10, 12,  4,  3])

In [34]:
matriz.min(1)

array([3, 5])

##### Pico mas alto al mas bajo
Obtine la diferencia numerica entre el valor mayor y el menor

In [36]:
print(arr)

[ 3 14 12  4  3  5 10 18  6 15]


El elemento menor es el 3 y el mayor es el 18
Del 3 al 18 hay una diferencia o pasos de 15 numeros.

In [37]:
arr.ptp()

15

In [38]:
print(matriz)

[[ 3 14 12  4  3]
 [ 5 10 18  6 15]]


In [39]:
matriz.ptp(1)

array([11, 13])

In [40]:
matriz.ptp(0)

array([ 2,  4,  6,  2, 12])

##### Operacion de Persentil
Cual es el valor que se encuentra en la mitad

In [41]:
print(arr)

[ 3 14 12  4  3  5 10 18  6 15]


In [42]:
np.percentile(arr, 50)

8.0

In [43]:
np.percentile(arr, 0)

3.0

In [44]:
np.percentile(arr, 100)

18.0

##### Ordenamiento
Con la funcion sort los elementos seran ordenados de acuerdo a su peso matematico

In [46]:
print(arr)
print(np.sort(arr))

[ 3 14 12  4  3  5 10 18  6 15]
[ 3  3  4  5  6 10 12 14 15 18]


#####  Mediana
Indica la mitad del array

In [47]:
print(arr)

[ 3 14 12  4  3  5 10 18  6 15]


In [48]:
np.median(arr)

8.0

In [49]:
np.median(matriz, 0)

array([ 4., 12., 15.,  5.,  9.])

In [50]:
np.median(matriz, 1)

array([ 4., 10.])

##### Desviacion estandar

In [51]:
np.std(arr)

5.2345009313209605

##### Varianza

In [52]:
np.var(arr)

27.4

##### Media
La suma de todos los valores 

In [53]:
np.mean(arr)

9.0

##### Concact

In [54]:
a = np.array([[1, 2,], [3, 4]])
b = np.array([4, 5])

A la funcion debemos pasarle los array a concatenar y el eje

In [56]:
#np.concatenate((a, b), axis=0)

Al ser distintas las dimensiones del array a con respecto al b retonr un error

In [61]:
a.ndim

2

In [59]:
b.ndim

1

Debemos redimensionar b para que sea de 2 dimensniones como a

In [62]:
b = np.expand_dims(b, axis=0)

Luego entonces es posible concatenar los array

In [64]:
print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]
 [4 5]]


Si en cambio queremos concatenar por eje 1, retorna otro error ya que la estructura de b es diferente al de a

In [66]:
#np.concatenate((a, b), axis=1)

In [69]:
print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[4 5]]


Podriamos realizar un reshape pero tambien existe una funcion llamada transpuesto que lo que hace es hacer a b como a es decir cambiarle la forma
La transpueste se expresa con la T mayuscula

In [71]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 4],
       [3, 4, 5]])

In [73]:
print(b)
print()
print(b.T)

[[4 5]]

[[4]
 [5]]


# Copy

In [74]:
import numpy as np

In [75]:
arr = np.arange(1, 12)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [76]:
trozo_arr = arr[0:6]
print(trozo_arr)

[1 2 3 4 5 6]


Suponiendo que el trozo d los primeros 5 valores necesitara que fueran 0, lo que ocurre sin usar la funcion copy de numpay es que el vector o arra original tambien cambia

In [78]:
trozo_arr[:] = 0
print(trozo_arr)
print(arr)

[0 0 0 0 0 0]
[ 0  0  0  0  0  0  7  8  9 10 11]


Esto ocurre porque aunque trozo_arr es nuevo este sigue haciendo referencia a arr por tanto a su referencia en memeoria.

Para evitarlo debemos invocar la funcion copy de numpy

In [81]:
arr_copy = arr.copy()
print(arr_copy)

[ 0  0  0  0  0  0  7  8  9 10 11]


In [85]:
arr_copy[:] = 100
print(arr_copy)

[100 100 100 100 100 100 100 100 100 100 100]


Copy respeta al vector o array original

In [84]:
print(arr)

[ 0  0  0  0  0  0  7  8  9 10 11]


# Condiciones

In [86]:
import numpy as np

Inicio, Fin, numero de valores tipo de datos de los valores

In [105]:
#Inicio, Fin, numero de valores tipo de datos de los valores
arr = np.linspace(1, 10, 10, dtype='int8')
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Condicionales

In [89]:
#mayores a 5
may_cinco = arr > 5
print(may_cinco)

[False False False False False  True  True  True  True  True]


In [91]:
print(arr[may_cinco])

[ 6  7  8  9 10]


Aquellos valores que sean mayor a 5 y ademas menores de 9

In [92]:
print(arr[(arr > 5) & (arr < 9)])

[6 7 8]


Para aquellos valores que sean mayores a cinco cambiar el valor a 99

In [94]:
arr[arr > 5] = 99
print(arr)

[ 1  2  3  4  5 99 99 99 99 99]


In [96]:
arr_disto_99 = arr[arr != 99]
print(arr_disto_99)

[1 2 3 4 5]


#### Where

In [104]:
matriz = np.array([[19,  4, 43],
       [ 8, 96, 80],
       [ 6, 99, 35]])
print(matriz)

print('Mientras en la matriz el valor sea mayor a 50 cambiar el valor por 0 y 1')
print(np.where(matriz > 50, 0, 1))

[[19  4 43]
 [ 8 96 80]
 [ 6 99 35]]
Mientras en la matriz el valor sea mayor a 50 cambiar el valor por 0 y 1
[[1 1 1]
 [1 0 0]
 [1 0 1]]


# Operaciones

In [106]:
import numpy as np

In [107]:
li = [1, 2]
print(li)

[1, 2]


In [108]:
li * 2

[1, 2, 1, 2]

Esta operacion no es tomada como lo deseado

In [138]:
arr = np.arange(0, 12)
print(arr)
arr_copy = arr.copy()

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [118]:
arr_copy = arr.copy()

## Operacion

In [139]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


###### Multiplicacion

In [140]:
print(arr * 2)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


###### Suma

In [141]:
print(arr + 2)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


###### Divison

In [142]:
print(11 / arr)

[        inf 11.          5.5         3.66666667  2.75        2.2
  1.83333333  1.57142857  1.375       1.22222222  1.1         1.        ]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


###### Exponenciacion

In [143]:
print(arr ** 2)

[  0   1   4   9  16  25  36  49  64  81 100 121]


###### Suma de array

In [144]:
print(arr)
print(arr_copy)
print('-' * 35)
print(arr + arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
-----------------------------------
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [145]:
print(arr)
print(arr_copy)
print('-' * 35)
print(arr * arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
-----------------------------------
[  0   1   4   9  16  25  36  49  64  81 100 121]


## Operacion con matrices

In [146]:
matriz = arr.reshape(2, 6)
matriz_copy = matriz.copy()

In [147]:
print(matriz)
print(matriz_copy)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


#### Operaciones

In [148]:
sum = matriz + matriz_copy
res = matriz - matriz_copy
mul = matriz * matriz_copy
div = matriz / matriz_copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [149]:
print(sum)
print(res)
print(mul)
print(div)

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[  0   1   4   9  16  25]
 [ 36  49  64  81 100 121]]
[[nan  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


#### Operacion algebraica producto punto
Para esta operacion necesita que los vectores o matrices tengan la misma estructura

In [152]:
print(matriz_copy.T)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [153]:
np.matmul(matriz, matriz_copy.T)

array([[ 55, 145],
       [145, 451]])

Otra manera

In [155]:
print(matriz @ matriz_copy.T)

[[ 55 145]
 [145 451]]


# Test

In [157]:
import numpy as np

In [158]:
np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])